Adding Matrix Action
mona-actions/gh-repo-stats pull request #11
Opened 2022-04-21 22:26 UTC by abelberhane

2022-04-21 22:43 UTC, ssulei7 commented
👍🏽 👍🏽

2022-04-21 22:43 UTC, ssulei7 approved these changes

2022-04-21 22:44 UTC, merged

2024-02-05 13:13 UTC, dandan3100 approved these changes
#!/usr/bin/env bash
echo "TODO implement this script."
echo "It should build binaries in dist/<platform>-<arch>[.exe] as needed."
exit 1

2024-02-05 13:13 UTC, dandan3100 requested changes
#!/usr/bin/env bash
echo "TODO implement this script."
echo "It should build binaries in dist/<platform>-<arch>[.exe] as needed."
exit 1