fix wrong argumnet in query
mona-actions/gh-repo-stats pull request #121
Opened 2024-12-12 23:36 UTC by amenocal

This pull request includes a change to the `GetTeams()` function in the `gh-repo-stats` file. The change modifies the GraphQL query to use the correct pagination parameter.

* [`gh-repo-stats`](diffhunk://#diff-2b8d8a0d1e785e1290f27228283ae8e24fada656da8369aa652e39270de448ffL1389-R1389): Modified the `GetTeams()` function to use `after` parameter for pagination instead of `endCursor`.

2024-12-14 18:20 UTC, ssulei7 approved these changes

2024-12-15 04:50 UTC, Meyydaa00 requested changes
Thanks

2024-12-16 15:27 UTC, merged

2025-01-11 23:47 UTC, mandervrik commented on gh-repo-stats
>          pageInfo {
creativecommons.com

2025-05-19 03:35 UTC, thekingznqueenz11 reviewed
[](https://github.com/mona-actions/gh-repo-stats/commit/fe988e7f7711a06e0283ae07e6b6c3ce5c899fa3)

2025-05-19 03:43 UTC, thekingznqueenz11 reviewed
fe988e7f7711a06e0283ae07e6b6c3ce5c899fa3)
[]()

2025-05-19 04:14 UTC, Psclmateo commented
Is me I just say I need money is a emergency you guys suks

El dom, 18 de may de 2025, 8:44 p. m., thekingznqueenz11 <
***@***.***> escribió:

> ***@***.**** commented on this pull request.
>
> fe988e7
> <https://github.com/mona-actions/gh-repo-stats/commit/fe988e7f7711a06e0283ae07e6b6c3ce5c899fa3>
> )
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mona-actions/gh-repo-stats/pull/121#pullrequestreview-2849305472>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BM5GV7GP7KOJGPCSE7NFG3L27FHQ7AVCNFSM6AAAAABTQ3Q6VGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDQNBZGMYDKNBXGI>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2025-05-19 04:16 UTC, Psclmateo commented
I hate everything and I send you to hate, I hate everything 😡

El dom, 18 de may de 2025, 9:14 p. m., Pascual Mateo ***@***.***>
escribió:

> Is me I just say I need money is a emergency you guys suks
>
> El dom, 18 de may de 2025, 8:44 p. m., thekingznqueenz11 <
> ***@***.***> escribió:
>
>> ***@***.**** commented on this pull request.
>>
>> fe988e7
>> <https://github.com/mona-actions/gh-repo-stats/commit/fe988e7f7711a06e0283ae07e6b6c3ce5c899fa3>
>> )
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/mona-actions/gh-repo-stats/pull/121#pullrequestreview-2849305472>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/BM5GV7GP7KOJGPCSE7NFG3L27FHQ7AVCNFSM6AAAAABTQ3Q6VGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDQNBZGMYDKNBXGI>
>> .
>> You are receiving this because you are subscribed to this thread.Message
>> ID: ***@***.***>
>>
>

2025-05-19 04:16 UTC, Psclmateo commented
I just say I need money is a emergency

El dom, 18 de may de 2025, 9:15 p. m., Pascual Mateo ***@***.***>
escribió:

> I hate everything and I send you to hate, I hate everything 😡
>
> El dom, 18 de may de 2025, 9:14 p. m., Pascual Mateo ***@***.***>
> escribió:
>
>> Is me I just say I need money is a emergency you guys suks
>>
>> El dom, 18 de may de 2025, 8:44 p. m., thekingznqueenz11 <
>> ***@***.***> escribió:
>>
>>> ***@***.**** commented on this pull request.
>>>
>>> fe988e7
>>> <https://github.com/mona-actions/gh-repo-stats/commit/fe988e7f7711a06e0283ae07e6b6c3ce5c899fa3>
>>> )
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/mona-actions/gh-repo-stats/pull/121#pullrequestreview-2849305472>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/BM5GV7GP7KOJGPCSE7NFG3L27FHQ7AVCNFSM6AAAAABTQ3Q6VGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDQNBZGMYDKNBXGI>
>>> .
>>> You are receiving this because you are subscribed to this thread.Message
>>> ID: ***@***.***>
>>>
>>

2025-06-08 22:10 UTC, adnanmohammed573 commented
So funny

2025-06-08 22:11 UTC, adnanmohammed573 reviewed
So funny

2025-06-21 16:12 UTC, quinonesholdingsllc commented
Quinonesholdingsllc@gmail.com is Francisco Quinones Jimenez properties